model-src:
    - example/model/**/*.model.yaml
    - example/implementation/**/*.model.yaml
config-src:
    - example/avifors/**/*.avifors.yaml
    - example/lib/**/*.avifors.yaml
plugins:
    - ./example/plugin.js
global:
    company_namespace: MyCorp
