event:
    arguments:
        name: string
        attributes: [string]
    outputs:
        -
            template: example/templates/event.php
            output: src/Event/{{ name | camelcase }}.php

events: [event]

events_test:
    arguments:
        events:
            -
                name: string
                attributes: [string]
    outputs: |
        {% for event in events %}
        -
            template: example/templates/event.php
            arguments: {{ event | json }}
            output: src/Event/{{ event.name | camelcase }}.php
        {% endfor %}

entities: [entity]
entity:
    arguments:
        name: string
        properties: [string]
    outputs:
        -
            template: example/templates/entity.php
            output: src/Entity/{{ name | camelcase }}.php
